/**
 * generated by Xtext 2.12.0
 */
package dbFactory.scoping;

import dbFactory.scoping.AbstractDbFactoryScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DbFactoryScopeProvider extends AbstractDbFactoryScopeProvider {
}
