/*
 * generated by Xtext 2.12.0
 */
package dbFactory.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDbFactoryValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dbFactory.dbFactory.DbFactoryPackage.eINSTANCE);
		return result;
	}
	
}
