/*
 * generated by Xtext 2.12.0
 */
package dbFactory.ui;

import com.google.inject.Injector;
import dbFactory.ui.internal.DbFactoryActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DbFactoryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DbFactoryActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DbFactoryActivator.getInstance().getInjector(DbFactoryActivator.DBFACTORY_DBFACTORY);
	}
	
}
