/**
 * generated by Xtext 2.12.0
 */
package dbFactory;

import dbFactory.DbFactoryStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DbFactoryStandaloneSetup extends DbFactoryStandaloneSetupGenerated {
  public static void doSetup() {
    new DbFactoryStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
