/*
 * generated by Xtext 2.12.0
 */
package dbFactory.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DbFactoryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dbFactory/parser/antlr/internal/InternalDbFactory.tokens");
	}
}
