/**
 * generated by Xtext 2.12.0
 */
package dbFactory.ide;

import dbFactory.ide.AbstractDbFactoryIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DbFactoryIdeModule extends AbstractDbFactoryIdeModule {
}
