/**
 * generated by Xtext 2.12.0
 */
package dbFactory.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dbFactory.DbFactoryRuntimeModule;
import dbFactory.DbFactoryStandaloneSetup;
import dbFactory.ide.DbFactoryIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DbFactoryIdeSetup extends DbFactoryStandaloneSetup {
  @Override
  public Injector createInjector() {
    DbFactoryRuntimeModule _dbFactoryRuntimeModule = new DbFactoryRuntimeModule();
    DbFactoryIdeModule _dbFactoryIdeModule = new DbFactoryIdeModule();
    return Guice.createInjector(Modules2.mixin(_dbFactoryRuntimeModule, _dbFactoryIdeModule));
  }
}
