/**
 * generated by Xtext 2.12.0
 */
package dbFactory.ui;

import dbFactory.ui.AbstractDbFactoryUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DbFactoryUiModule extends AbstractDbFactoryUiModule {
  public DbFactoryUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
