/*
 * generated by Xtext 2.12.0
 */
package dbFactory.ui.tests;

import com.google.inject.Injector;
import dbFactory.ui.internal.DbFactoryActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DbFactoryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DbFactoryActivator.getInstance().getInjector("dbFactory.DbFactory");
	}

}
