/*
 * generated by Xtext 2.12.0
 */
package dbFactory


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DbFactoryStandaloneSetup extends DbFactoryStandaloneSetupGenerated {

	def static void doSetup() {
		new DbFactoryStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
