/**
 * generated by Xtext 2.12.0
 */
package dbFactory.tests;

import com.google.inject.Inject;
import dbFactory.dbFactory.Model;
import dbFactory.tests.DbFactoryInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DbFactoryInjectorProvider.class)
@SuppressWarnings("all")
public class DbFactoryParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Objekt Person{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Alter: Zahl.");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("Name: text.");
      _builder.newLine();
      _builder.append("}.");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
