/**
 * generated by Xtext 2.12.0
 */
package dbFactory.validation;

import dbFactory.dbFactory.Command;
import dbFactory.validation.AbstractDbFactoryValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DbFactoryValidator extends AbstractDbFactoryValidator {
  @Check
  public Object checkCommandStartsWithCapital(final Command command) {
    return null;
  }
}
