/**
 * generated by Xtext 2.12.0
 */
package dbFactory.validation;

import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DbFactoryValidator /* implements AbstractDbFactoryValidator  */{
  @Check
  public Object checkCommandStartsWithCapital(final /* Command */Object command) {
    return null;
  }
}
