/**
 * generated by Xtext 2.12.0
 */
package dbFactory.dbFactory;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dbFactory.dbFactory.Command#getObj <em>Obj</em>}</li>
 * </ul>
 *
 * @see dbFactory.dbFactory.DbFactoryPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' containment reference.
   * @see #setObj(dbFactory.dbFactory.Object)
   * @see dbFactory.dbFactory.DbFactoryPackage#getCommand_Obj()
   * @model containment="true"
   * @generated
   */
  dbFactory.dbFactory.Object getObj();

  /**
   * Sets the value of the '{@link dbFactory.dbFactory.Command#getObj <em>Obj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' containment reference.
   * @see #getObj()
   * @generated
   */
  void setObj(dbFactory.dbFactory.Object value);

} // Command
