/**
 * generated by Xtext 2.12.0
 */
package dbFactory.dbFactory;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dbFactory.dbFactory.DbFactoryFactory
 * @model kind="package"
 * @generated
 */
public interface DbFactoryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dbFactory";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.DbFactory.dbFactory";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dbFactory";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DbFactoryPackage eINSTANCE = dbFactory.dbFactory.impl.DbFactoryPackageImpl.init();

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.ModelImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMAND = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.CommandImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__OBJ = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.ObjectImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__SUPER_TYPE = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__ATTRIBUTES = 2;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.AttributeImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.AttributeTypeImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getAttributeType()
   * @generated
   */
  int ATTRIBUTE_TYPE = 4;

  /**
   * The feature id for the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__ELEMENT_TYPE = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__LENGTH = 2;

  /**
   * The number of structural features of the '<em>Attribute Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.ElementTypeImpl <em>Element Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.ElementTypeImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getElementType()
   * @generated
   */
  int ELEMENT_TYPE = 5;

  /**
   * The number of structural features of the '<em>Element Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.StandartTypeImpl <em>Standart Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.StandartTypeImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getStandartType()
   * @generated
   */
  int STANDART_TYPE = 6;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDART_TYPE__TYPE_NAME = ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Standart Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STANDART_TYPE_FEATURE_COUNT = ELEMENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dbFactory.dbFactory.impl.ObjectTypeImpl <em>Object Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dbFactory.dbFactory.impl.ObjectTypeImpl
   * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getObjectType()
   * @generated
   */
  int OBJECT_TYPE = 7;

  /**
   * The feature id for the '<em><b>Type Obj</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE__TYPE_OBJ = ELEMENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_TYPE_FEATURE_COUNT = ELEMENT_TYPE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see dbFactory.dbFactory.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link dbFactory.dbFactory.Model#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Command</em>'.
   * @see dbFactory.dbFactory.Model#getCommand()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Command();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see dbFactory.dbFactory.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference '{@link dbFactory.dbFactory.Command#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see dbFactory.dbFactory.Command#getObj()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Obj();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see dbFactory.dbFactory.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the attribute '{@link dbFactory.dbFactory.Object#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dbFactory.dbFactory.Object#getName()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_Name();

  /**
   * Returns the meta object for the reference '{@link dbFactory.dbFactory.Object#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see dbFactory.dbFactory.Object#getSuperType()
   * @see #getObject()
   * @generated
   */
  EReference getObject_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link dbFactory.dbFactory.Object#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see dbFactory.dbFactory.Object#getAttributes()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Attributes();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see dbFactory.dbFactory.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link dbFactory.dbFactory.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dbFactory.dbFactory.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link dbFactory.dbFactory.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see dbFactory.dbFactory.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.AttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Type</em>'.
   * @see dbFactory.dbFactory.AttributeType
   * @generated
   */
  EClass getAttributeType();

  /**
   * Returns the meta object for the containment reference '{@link dbFactory.dbFactory.AttributeType#getElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element Type</em>'.
   * @see dbFactory.dbFactory.AttributeType#getElementType()
   * @see #getAttributeType()
   * @generated
   */
  EReference getAttributeType_ElementType();

  /**
   * Returns the meta object for the attribute '{@link dbFactory.dbFactory.AttributeType#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see dbFactory.dbFactory.AttributeType#isArray()
   * @see #getAttributeType()
   * @generated
   */
  EAttribute getAttributeType_Array();

  /**
   * Returns the meta object for the attribute '{@link dbFactory.dbFactory.AttributeType#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see dbFactory.dbFactory.AttributeType#getLength()
   * @see #getAttributeType()
   * @generated
   */
  EAttribute getAttributeType_Length();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.ElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Type</em>'.
   * @see dbFactory.dbFactory.ElementType
   * @generated
   */
  EClass getElementType();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.StandartType <em>Standart Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Standart Type</em>'.
   * @see dbFactory.dbFactory.StandartType
   * @generated
   */
  EClass getStandartType();

  /**
   * Returns the meta object for the attribute '{@link dbFactory.dbFactory.StandartType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see dbFactory.dbFactory.StandartType#getTypeName()
   * @see #getStandartType()
   * @generated
   */
  EAttribute getStandartType_TypeName();

  /**
   * Returns the meta object for class '{@link dbFactory.dbFactory.ObjectType <em>Object Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Type</em>'.
   * @see dbFactory.dbFactory.ObjectType
   * @generated
   */
  EClass getObjectType();

  /**
   * Returns the meta object for the reference '{@link dbFactory.dbFactory.ObjectType#getTypeObj <em>Type Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type Obj</em>'.
   * @see dbFactory.dbFactory.ObjectType#getTypeObj()
   * @see #getObjectType()
   * @generated
   */
  EReference getObjectType_TypeObj();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DbFactoryFactory getDbFactoryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.ModelImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMAND = eINSTANCE.getModel_Command();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.CommandImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__OBJ = eINSTANCE.getCommand_Obj();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.ObjectImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__NAME = eINSTANCE.getObject_Name();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__SUPER_TYPE = eINSTANCE.getObject_SuperType();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__ATTRIBUTES = eINSTANCE.getObject_Attributes();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.AttributeImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.AttributeTypeImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getAttributeType()
     * @generated
     */
    EClass ATTRIBUTE_TYPE = eINSTANCE.getAttributeType();

    /**
     * The meta object literal for the '<em><b>Element Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_TYPE__ELEMENT_TYPE = eINSTANCE.getAttributeType_ElementType();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_TYPE__ARRAY = eINSTANCE.getAttributeType_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_TYPE__LENGTH = eINSTANCE.getAttributeType_Length();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.ElementTypeImpl <em>Element Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.ElementTypeImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getElementType()
     * @generated
     */
    EClass ELEMENT_TYPE = eINSTANCE.getElementType();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.StandartTypeImpl <em>Standart Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.StandartTypeImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getStandartType()
     * @generated
     */
    EClass STANDART_TYPE = eINSTANCE.getStandartType();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STANDART_TYPE__TYPE_NAME = eINSTANCE.getStandartType_TypeName();

    /**
     * The meta object literal for the '{@link dbFactory.dbFactory.impl.ObjectTypeImpl <em>Object Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dbFactory.dbFactory.impl.ObjectTypeImpl
     * @see dbFactory.dbFactory.impl.DbFactoryPackageImpl#getObjectType()
     * @generated
     */
    EClass OBJECT_TYPE = eINSTANCE.getObjectType();

    /**
     * The meta object literal for the '<em><b>Type Obj</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_TYPE__TYPE_OBJ = eINSTANCE.getObjectType_TypeObj();

  }

} //DbFactoryPackage
