/**
 * generated by Xtext 2.12.0
 */
package dbFactory.dbFactory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dbFactory.dbFactory.ObjectType#getTypeObj <em>Type Obj</em>}</li>
 * </ul>
 *
 * @see dbFactory.dbFactory.DbFactoryPackage#getObjectType()
 * @model
 * @generated
 */
public interface ObjectType extends ElementType
{
  /**
   * Returns the value of the '<em><b>Type Obj</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Obj</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Obj</em>' reference.
   * @see #setTypeObj(dbFactory.dbFactory.Object)
   * @see dbFactory.dbFactory.DbFactoryPackage#getObjectType_TypeObj()
   * @model
   * @generated
   */
  dbFactory.dbFactory.Object getTypeObj();

  /**
   * Sets the value of the '{@link dbFactory.dbFactory.ObjectType#getTypeObj <em>Type Obj</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Obj</em>' reference.
   * @see #getTypeObj()
   * @generated
   */
  void setTypeObj(dbFactory.dbFactory.Object value);

} // ObjectType
