/**
 * generated by Xtext 2.12.0
 */
package dbFactory.dbFactory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Standart Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dbFactory.dbFactory.StandartType#getTypeName <em>Type Name</em>}</li>
 * </ul>
 *
 * @see dbFactory.dbFactory.DbFactoryPackage#getStandartType()
 * @model
 * @generated
 */
public interface StandartType extends ElementType
{
  /**
   * Returns the value of the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' attribute.
   * @see #setTypeName(String)
   * @see dbFactory.dbFactory.DbFactoryPackage#getStandartType_TypeName()
   * @model
   * @generated
   */
  String getTypeName();

  /**
   * Sets the value of the '{@link dbFactory.dbFactory.StandartType#getTypeName <em>Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' attribute.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(String value);

} // StandartType
