/**
 * generated by Xtext 2.12.0
 */
package dbFactory.ui.contentassist;

import dbFactory.ui.contentassist.AbstractDbFactoryProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DbFactoryProposalProvider extends AbstractDbFactoryProposalProvider {
}
